---
blank_issues_enabled: false
contact_links:
  - name: Amazing GitHub Template Community Support
    url: https://github.com/dan5e3s6ares/a-real-mock-api/discussions
    about: Please ask and answer questions here.
