name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code-quality:
    uses: dan5e3s6ares/git_actions_workflows/.github/workflows/code-quality.yaml@main
    with:
      platform: "docker-compose"
